/**
 * ISO 4217 currency code, e.g. "SGD", "USD", "JPY".
 * We keep this as a string so the watchlist can be dynamic.
 */
export type CurrencyCode = string;

/** Supported chart ranges for the time-series endpoint/UI. */
export type TimeRange = "1D" | "1W" | "1M" | "3M" | "6M" | "1Y";

/** Standard API error payload used by our route handlers. */
export interface ApiError {
  error: string;
}

/**
 * Latest exchange rates response.
 * Interpreted as: 1 <base> converts to <rates[code]> <code>.
 */
export interface LatestRates {
  base: CurrencyCode; // e.g. "SGD"
  /** ISO timestamp when this response was generated by our API */
  asOf: string;
  /** Map of currency code -> rate */
  rates: Record<CurrencyCode, number>;
  /** YYYY-MM-DD from upstream (if available) */
  providerDate?: string;
  /** symbols requested/returned */
  symbols?: CurrencyCode[];
}

/**
 * One data point in a time series.
 * `t` uses YYYY-MM-DD (Frankfurter uses dates, not timestamps).
 */
export interface TimeSeriesPoint {
  t: string; // e.g. "2026-02-01"
  v: number;
}

/**
 * Historical time-series response.
 * Interpreted as: 1 <base> converts to <v> <symbol> at date <t>.
 */
export interface TimeSeries {
  base: CurrencyCode; // e.g. "SGD"
  symbol: CurrencyCode; // e.g. "JPY"
  /** ISO timestamp when this response was generated by our API */
  asOf: string;
  points: TimeSeriesPoint[];
  range?: TimeRange;
  /** YYYY-MM-DD */
  from?: string;
  /** YYYY-MM-DD */
  to?: string;
}

/**
 * Optional helper type for a persisted watchlist item.
 * (We keep this minimal; UI can derive labels separately.)
 */
export interface WatchlistItem {
  code: CurrencyCode;
}
